### ISSUE TITLE
Leap Seconds for 2022 and future

### ISSUE THREAD

**Issue by wewa00** [pingswept/pysolar#152]
Hi, is it possible to add the leap seconds for 2022 and the upcoming years please ?

Message : UserWarning: I don't know about leap seconds after 2021
warnings.warn \

Thank you very much !

**Comment by pingswept** [comment]
The 2022 leap second data has been added to the latest code; you’ll have to figure out how to upgrade to that, or just add (0,0) to solartime.py by hand. Here it is: https://github.com/pingswept/pysolar/blob/5e4796604b4c7b38713f19faa5843b1569dd6ead/pysolar/solartime.py#L92

We can’t add future adjustments because we don’t know how much the earth will slow down yet. It’s affected by tidal sloshing, glacial rebound, and other things that I don’t know about. For reference: https://en.wikipedia.org/wiki/Leap_second
