### ISSUE TITLE
Day length based on solar altitude.

### ISSUE THREAD

**Issue by arnaldorusso** [pingswept/pysolar#16]
Hi Brandon,
Is there any function implemented on Pysolar, which day length could be computed based on specific sun Altitude as boundary limits?

Thank you,
Arnaldo.

**Comment by DouglasAllen** [comment]
You will want be more specific if you do this because there are four standards for each horizon to zenith angle. Official takes into account for parallax and semi-diameter of the solar disk. Then Civil, Nautical, and Astronomical twilight start and end. Maybe I'm not on topic here but that has been my experience as I have no idea how accurate you're needing this to be. There are two basic methods that I'm aware of for longitudinal transit. One uses equation of time and the other is to use sidereal time based on right ascension of local longitude. But yes you could name parts of your function 'diurnal arc' then just split it two but that is not taking into account any motion change of the Earth throughout the day. I haven't seen anyone try to compensate for such changes in any code yet but there is a very small amount. Perhaps take a couple of calculations for rise and set with equation of time factored in. It is not just for transit time. Good coding. 
![analemma_earth](https://cloud.githubusercontent.com/assets/887598/21968794/3eb41ae4-db5e-11e6-9422-e52cfc9d0392.png)

**Comment by pingswept** [comment]
Closing due to staleness. Arnaldo, feel free to open again, or start a new issue, if you want.
