### ISSUE TITLE
Values are slightly off

### ISSUE THREAD

**Issue by jvhaarst** [pingswept/pysolar#64]
I'm trying to create a solar path graph, and what I see is that instead of a nice smooth transition I get kinks.
So instead of 
![ravsunimage10](https://user-images.githubusercontent.com/52068/34710361-4286147e-f51b-11e7-819c-b16815b5aa1d.jpg)

(from https://permaculturenews.org/wp-content/uploads/2015/10/ravsunImage10.jpg)

I get 
![download](https://user-images.githubusercontent.com/52068/34710374-4d3f4926-f51b-11e7-9238-442178e216b6.png)

Code is here : https://gist.github.com/jvhaarst/6ee7c6c5972afcddfa1904777fe7d5a8

Are the path that I calculate the truth, and thus the other ones an perfection, or is pysolar slightly off when calculating the positions ?

**Comment by pingswept** [comment]
It looks to me like the kinks are just in the hour contour lines, not in the trajectories of the sun, which look smooth. I'd guess that's because you have only 7 data points for each hour, and matplotlib is connecting them with straight lines. (I think-- am I right about the 7 data points? Or how are you interpolating between months?) 

As far as general accuracy, some efforts at validation are here: http://docs.pysolar.org/en/latest/#validation A rough summary would be that "The azimuth estimations correlated much more closely than the altitude estimations, but both agreed with [those of the US Naval Observatory] to within less than 0.1 degrees on average." We don't really know which party is closer to the truth.

**Comment by jvhaarst** [comment]
It's a lot simpler than that, the kinks are true, as the annalemma is plotted not smooth.

If I do that (soomed in to noon), I get this : 
![clipboard01](https://user-images.githubusercontent.com/52068/34826473-f7f886c2-f6d6-11e7-8929-a654bab21387.png)

So the library performs as expected, the solar path graphs that are used elsewhere are simplified.
The accuracy doesn't come into play, as all data is "wrong".

**Comment by jvhaarst** [comment]
For me this is fixed, so I'm closing this now.
