### ISSUE TITLE
PATH requirements for use in Windows

### ISSUE THREAD

**Issue by skiddaw** [pingswept/pysolar#82]
I'm trying to get pysolar to work on a Win7 laptop but am having no luck 'finding' e.g. get_altitude.  Might a "Windows" heading be added to the manual with a short description of what needs appending to PATH or PYTHONPATH etc.  i.e. what file is in the folder I need to direct PATH to?

**Comment by efiring** [comment]
There should be no need to add anything to PYTHONPATH, on Windows or on any other platform.  (PATH is irrelevant here.) When the package is installed, it goes in a standard location that is known to the python version used to install it.  Therefore the possible problems are (1) if you have more than one python version, you might be trying to import with one version when the installation was another version, or (2) there is confusion as to the  name of the package and the names of the modules and functions within it.  I think (2) is most likely, because there have been big changes in naming from 0.6 to 0.7 and then to 0.8-RC1.

**Comment by pingswept** [comment]
Not an issue with the Pysolar library itself. Closing.
