### ISSUE TITLE
Astral comparison

### ISSUE THREAD

**Issue by paulocheque** [pingswept/pysolar#91]
The doc comparing PySolar with PyEphem and SunPy are awesome! Do you have some differences related to the Astral library too? https://github.com/sffjunkie/astral

**Comment by pingswept** [comment]
Just looked at Astral. It appears to be Pysolar in reverse, i.e. instead of telling you where the sun is at a certain time, it tells you when a certain atmospheric event will occur (like sunrise or sunset). To do that, it does need to calculate the location of the sun, but it appears to use a rougher approximation than Pysolar. The Astral's azimuth code, about 100 lines, is here: https://github.com/sffjunkie/astral/blob/master/src/astral.py#L2009
For comparison, Pysolar has approximately 400 lines of just constants used to adjust for aberrations like the moon swinging the earth out of a purely elliptical orbit around the sun: https://github.com/pingswept/pysolar/blob/master/pysolar/constants.py

Listing a bunch of numbers in a file doesn't necessarily make Pysolar more accurate, but it probably is.

Also, I should probably add that all the mathematics of Pysolar is from an NREL paper (https://www.osti.gov/biblio/15003974); I just implemented their algorithm in Python.

If anyone wants to compare the error between Pysolar and Astral, I'd be interested to add that to the documentation.

**Comment by paulocheque** [comment]
Awesome feedback! I imagine that, because Astral performance to get the azimuth and altitude is waaay faster, so I imagine the calculation would be less precise, although the difference is very small.

If I have a more serious comparison I will definitely post it here, thanks again!
